export const data = [
  {
    id: 1,
    imgSrc: './categories/1.jpg',
    category: 'necklaces',
    href: '',
    title: 'Birds of Paradise Pendant',
    desc: 'A beautiful pendant inspired by the exotic Birds of Paradise.',
    price: 199.99,
    comparePrice: 249.99,
    rating: 4.5,
  },
  {
    id: 2,
    imgSrc: './categories/2.jpg',
    category: 'rings',
    href: '',
    title: 'Eternal Love Ring',
    desc: 'A symbol of everlasting love, crafted with precision and care.',
    price: 299.0,
    rating: 4.8,
  },
  {
    id: 3,
    imgSrc: './categories/3.jpg',
    category: 'bracelets',
    href: '',
    title: 'Ocean Breeze Bracelet',
    desc: 'Capture the essence of the ocean with this elegant bracelet.',
    price: 149.5,
    comparePrice: 179.99,
    rating: 4.2,
  },
  {
    id: 4,
    imgSrc: './categories/4.jpg',
    category: 'earrings',
    href: '',
    title: 'Starlight Earrings',
    desc: 'Shine like the stars with these delicate and sparkling earrings.',
    price: 129.0,
    rating: 4.6,
  },
  {
    id: 5,
    imgSrc: './categories/5.jpg',
    category: 'charm & dangles',
    href: '',
    title: 'Lucky Clover Charm',
    desc: 'Bring good fortune with this charming clover dangle.',
    price: 49.99,
    rating: 4.0,
  },
]
