const base = process.env.CLOUDINARY_BASE_URL;

export const products = [
  // Rings
  {
    title: "Vintage Sapphire Ring",
    slug: "vintage-sapphire-ring",
    description: "Elegant vintage-style ring with a blue sapphire stone.",
    price: 59.99,
    compareprice: 79.99,
    image: `${base}/image/upload/v1747921118/ecommerce/rings/bekvob3jrns7w9lfmufa.jpg`,
    category: "Rings",
    rating: 4.8,
  },
  {
    title: "Classic Gold Band",
    slug: "classic-gold-band",
    description: "Timeless gold band for any occasion.",
    price: 99.0,
    compareprice: 120.0,
    image: `${base}/image/upload/v1747921118/ecommerce/rings/b8b7ffta18pzhhymakrn.jpg`,
    category: "Rings",
    rating: 4.6,
  },
  {
    title: "Diamond Engagement Ring",
    slug: "diamond-engagement-ring",
    description: "Stunning diamond ring for special proposals.",
    price: 299.99,
    compareprice: 349.99,
    image: `${base}/image/upload/v1747921118/ecommerce/rings/a27ulosrmlb620n7kc2b.jpg`,
    category: "Rings",
    rating: 4.9,
  },
  {
    title: "Silver Knot Ring",
    slug: "silver-knot-ring",
    description: "Symbolic knot design in pure silver.",
    price: 29.99,
    compareprice: 39.99,
    image: `${base}/image/upload/v1747921118/ecommerce/rings/fdwfbc2d4wlmnlbguol8.jpg`,
    category: "Rings",
    rating: 4.5,
  },
  {
    title: "Rose Gold Band",
    slug: "rose-gold-ring",
    description: "Beautiful ring with a polished gemstone.",
    price: 45.0,
    compareprice: 55.0,
    image: `${base}/image/upload/v1747921118/ecommerce/rings/ebgq2xafvqi75siaftqw.jpg`,
    category: "Rings",
    rating: 4.4,
  },

  // Charms-Dangles
  {
    title: "Heart Charm Pendant",
    slug: "heart-charm-pendant",
    description: "Sterling silver heart charm.",
    price: 24.99,
    compareprice: 34.99,
    image: `${base}/image/upload/v1747921671/ecommerce/charms_dangles/bh4l7ymd1osxocapvunn.webp`,
    category: "Charms-Dangles",
    rating: 4.9,
  },
  {
    title: "Star Dangle Charm",
    slug: "star-dangle-charm",
    description: "Dangling star charm with enamel coating.",
    price: 19.5,
    compareprice: 25.0,
    image: `${base}/image/upload/v1747921670/ecommerce/charms_dangles/byupckreqszf6eee7d9g.jpg`,
    category: "Charms-Dangles",
    rating: 4.4,
  },
  {
    title: "Birthstone Charm",
    slug: "birthstone-charm",
    description: "Customizable birthstone dangle.",
    price: 29.99,
    compareprice: 39.99,
    image: `${base}/image/upload/v1747921670/ecommerce/charms_dangles/ul3qssdfaoi4t3mtnzfw.jpg`,
    category: "Charms-Dangles",
    rating: 4.8,
  },
  {
    title: "Butterfly Charm",
    slug: "butterfly-charm",
    description: "Whimsical butterfly charm in rose gold.",
    price: 22.99,
    compareprice: 29.99,
    image: `${base}/image/upload/v1747921670/ecommerce/charms_dangles/sjxzedb6cj2ekfzdvsex.webp`,
    category: "Charms-Dangles",
    rating: 4.5,
  },
  {
    title: "Infinity Dangle Charm",
    slug: "infinity-dangle-charm",
    description: "Symbolic infinity dangle charm.",
    price: 26.0,
    compareprice: 35.0,
    image: `${base}/image/upload/v1747921671/ecommerce/charms_dangles/ioludbfkg16ohpxxqgiq.jpg`,
    category: "Charms-Dangles",
    rating: 4.6,
  },

  // Necklaces
  {
    title: "Minimalist Gold Necklace",
    slug: "minimalist-gold-necklace",
    description: "Delicate 14K gold necklace.",
    price: 74.5,
    compareprice: 99.99,
    image: `${base}/image/upload/v1747922555/ecommerce/necklases/ypdkv5rhoatgazmihkyo.webp`,
    category: "Necklaces",
    rating: 4.6,
  },
  {
    title: "Silver Circle Pendant",
    slug: "silver-circle-pendant",
    description: "Simple and elegant circle pendant in silver.",
    price: 34.99,
    compareprice: 44.99,
    image: `${base}/image/upload/v1747922555/ecommerce/necklases/mw3wb90qma6zxoisidll.jpg`,
    category: "Necklaces",
    rating: 4.5,
  },
  {
    title: "Pearl Strand Necklace",
    slug: "pearl-strand-necklace",
    description: "Classic strand of white pearls.",
    price: 129.99,
    compareprice: 159.99,
    image: `${base}/image/upload/v1747922555/ecommerce/necklases/mbbass24sonw8inyl0na.webp`,
    category: "Necklaces",
    rating: 4.7,
  },
  {
    title: "Infinity Symbol Necklace",
    slug: "infinity-symbol-necklace",
    description: "Infinity symbol pendant in rose gold.",
    price: 49.95,
    compareprice: 59.95,
    image: `${base}/image/upload/v1747922555/ecommerce/necklases/cawbgykrsbptdeaitqfk.jpg`,
    category: "Necklaces",
    rating: 4.6,
  },
  {
    title: "Layered Chain Necklace",
    slug: "layered-chain-necklace",
    description: "Fashionable layered chains in gold tone.",
    price: 39.99,
    compareprice: 49.99,
    image: `${base}/image/upload/v1747922555/ecommerce/necklases/xo0j3vitfxi5irlvolbj.webp`,
    category: "Necklaces",
    rating: 4.4,
  },
];
